#pragma once

#include "wx/defs.h"

enum 
{
	//控件id
	GW_CTRL_BEGIN = wxID_HIGHEST,
	CTRL_TEE_SET_TAG,
	CTRL_TEE_TAG_OK,
	CTRL_TEE_TAG_CHECKBOX,
	CTRL_TEE_DIALOG_DISPLAY_NAME,
	CTRL_TEE_DIALOG_CODE_NAME,
	CTRL_FUNCTION_DIALOG_RETURN_CLASSFIY,
	CTRL_FUNCTION_DIALOG_RETURN_TYPE,
	CTRL_FUNCTION_DIALOG_RETURN_DETAIL,
	CTRL_ECA_TREE,
	CTRL_ECA_EDIT,
	CTRL_ECA_VIEW,
	CTRL_TEE_INCLUDE_OK,
	CTRL_TEE_INCLUDE_CHECKBOX,
	GW_CTRL_END,

	//菜单id
	GW_MENU_TEE_BEGIN = GW_CTRL_END+1,
	GW_MENU_END,

	//自定义其它
	GW_CUSTOM_BEGIN =GW_MENU_END+1,
	GW_CUSTOM_END,

	GW_ID_END,

};