#pragma once

#include "wx/defs.h"
enum 
{
	//控件id
	TGR_CTRL_BEGIN = wxID_HIGHEST,
	TGR_FRAME_ID,
	TGR_FRAME_BAR_VARIABLE,
	TGR_CLASSIFY_TREE,
	TGR_TRIGGER_TREE,
	TGR_SEARCH_EDIT,
	TGR_SET_EVENT_OK,
	TGR_SET_EVENT_CANCEL,
	STATEMENTDLG_SEARCH_EDIT,
	STATEMENTDLG_CHOICE_STATEMENT,
	TGR_MAIN_HYPERLINK,
	PARAMDLG_COMBO_ADJUST,
	PARAMDLG_CHOICE_CONTEXT_VARIABLE,
	PARAMDLG_CHOICE_LOCAL_VARIABLE,
	PARAMDLG_CHOICE_PARAM_VARIABLE,
	PARAMDLG_CHOICE_GLOBAL_VARIABLE,
	TGR_PREFERENCES_ADJUST_VAREDIT,
	TGR_PREFERENCES_EDIT_OPTION_BUTTON,
	PARAMDLG_CHOICE_FUNCTION,
	PARAMDLG_EDIT_VALUE,
	PARAMDLG_BOOL_VALUE,
	TGR_PREF_OK,
	TGR_PREF_CANCEL,
	TGR_VAR_EDIT_NAME,
	TGR_VAR_EDIT_TYPE,
	TGR_VAR_EDIT_DEFAULT_VALUE,
	TGR_VAR_EDIT_CHECK_ARY,
	TGR_VAR_EDIT_CLEAR_DEFAULT,
	TGR_OPTION_EDIT,
	TGR_SELECT_OPTION,
	TGR_SPACES_CHOICE,
	TGR_PUBLISH,
	TGR_CONNECT,
	TGR_DISCONNECT,
	TGR_CTRL_END,

	//菜单id
	TGR_MENU_TEE_BEGIN = TGR_CTRL_END+1,

	TGR_CLASSIFY_TREE_CUT,
	TGR_CLASSIFY_TREE_COPY,
	TGR_CLASSIFY_TREE_PASTE,
	TGR_CLASSIFY_TREE_DELETE,
	TGR_CLASSIFY_TREE_NEW_GROUP,
	TGR_CLASSIFY_TREE_NEW_TRIGGER,
	TGR_CLASSIFY_TREE_NEW_FUNCTION,
	TGR_CLASSIFY_TREE_EMPLOY,
	TGR_CLASSIFY_TREE_NEW_EVENT,
	TGR_CLASSIFY_TREE_NEW_CONDITION,
	TGR_CLASSIFY_TREE_NEW_ACTION,
	TGR_CLASSIFY_TREE_PERMIT,

	TGR_TRIGGER_TREE_CUT,
	TGR_TRIGGER_TREE_COPY,
	TGR_TRIGGER_TREE_PASTE,
	TGR_TRIGGER_TREE_DELETE,
	TGR_TRIGGER_TREE_NEW_EVENT,
	TGR_TRIGGER_TREE_NEW_CONDITION,
	TGR_TRIGGER_TREE_NEW_PARAM,
	TGR_TRIGGER_TREE_NEW_ACTION,
	TGR_TRIGGER_TREE_NEW_VARIABLE,
	TGR_TRIGGER_TREE_PERMIT,

	TGR_VARLIST_NEW,
	TGR_VARLIST_EDIT,
	TGR_VARLIST_DELETE,

	TGR_MENU_END,

	//自定义其它
	TGR_CUSTOM_BEGIN = TGR_MENU_END+1,
	TGR_CUSTOM_MENU_APPENDSEPARATOR,

};