#pragma once

#include "wx/defs.h"
#include "GWIDs.h"

enum 
{
	//控件id
	CTRL_BEGIN = GW_ID_END,
	CTRL_TEE_OPTION_LIST,
	CTRL_TEE_ADJUST_LIST,
	CTRL_TEE_ADD_PARAM,
	CTRL_END,

	//菜单id
	MENU_TEE_BEGIN = CTRL_END+1,
	MENU_TEE_NEW_EVENT,
	MENU_TEE_NEW_CONDITION,
	MENU_TEE_NEW_FUNCTION,
	MENU_TEE_NEW_OPTION,
	MENU_TEE_NEW_SPACE,
	MENU_TEE_DELETE,
	MENU_TEE_PROPERTY,
	MENU_TEE_SAVE,
	MENU_END,

	//自定义其它
	CUSTOM_BEGIN = MENU_END+1,
	CUSTOM_MENU_APPENDSEPARATOR,

};